--- #YAML:1.0
name:               Net-CIDR-ORTC
version:            0.02
abstract:           CIDR map compression
author:
    - Anton Yuzhaninov <ayuzhaninov@openstat.ru>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:  0
resources:
    bugtracker:  https://bitbucket.org/citrin/p5-net-cidr-ortc/issues
    license:     http://dev.perl.org/licenses/
    repository:  https://bitbucket.org/citrin/p5-net-cidr-ortc/src
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
