---
abstract: 'CIDR map compression'
author:
  - 'Anton Yuzhaninov <ayuzhaninov@openstat.ru>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CIDR-ORTC
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
resources:
  bugtracker: https://bitbucket.org/citrin/p5-net-cidr-ortc/issues
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/citrin/p5-net-cidr-ortc/src
version: 0.01
